#version: "3.8"

services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=romanpi.ddns.net

      # ⚠️ Change the Web UI Password:
      - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG
#      - PASSWORD_HASH=$$2a$12$q8ZAoDTOZHM5FaXIFBAPZumqPNkIZHI1abLZjAGxMaMrI/qWrL1PW
#      - PASSWORD=RoMaN
      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

  wg-pihole:
    image: pihole/pihole
    container_name: wg-pihole
    environment:
      # ⚠️ Change the Web UI Password:
      - WEBPASSWORD=RoMaN
    volumes:
      - '~/docker/wgeasy/.pihole/etc-pihole:/etc/pihole'
      - '~/docker/wgeasy/.pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3
  
  # wg-homebridge:
  #   image: homebridge/homebridge:latest
  #   container_name: wg-homebridge
  #   restart: always
  #   # network_mode: host
  #   volumes:
  #     - ~/docker/homebridge/volumes/homebridge:/homebridge
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10mb"
  #       max-file: "1"
  #   ports:
  #    - "8581:8581/tcp"
  #    - "51854:51854/tcp"
  #    - "51827:51827/tcp"
  #    - "52620:52620/tcp"
  #   networks:
  #     wg-easy:
  #       ipv4_address: 10.8.1.4


networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
