# NOTA IMPORTANTE: Los directorios deben estar creados antes porque se acceden con root y si no lo estan se crean con root
---
version: "3.7"
services:
  # https://github.com/haugene/docker-transmission-openvpn
  # transmission:
  #   image: haugene/transmission-openvpn:latest
  #   container_name: transmission
  #   restart: always
  #   ports:
  #     - "9091:9091"
  #   # https://haugene.github.io/docker-transmission-openvpn/config-options/
  #   environment:
  #     # - OPENVPN_PROVIDER=<FILL>
  #     # - OPENVPN_CONFIG=<FILL>
  #     # - OPENVPN_USERNAME=<FILL>
  #     # - OPENVPN_PASSWORD=<FILL>
  #     # - WEBPROXY_ENABLED=false
  #     - LOCAL_NETWORK=192.168.1.0/24
  #     - TRANSMISSION_WEB_UI=flood-for-transmission
  #   volumes:
  #     - /media/arrfam/downloads:/data
  #     - /etc/localtime:/etc/localtime:ro
  #   cap_add:
  #     - NET_ADMIN

  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Madrid
    volumes:
      - ~/docker/arrfam/.radarr:/config
      - /home/roman/media/arrfam/movies:/movies
      - /home/roman/downloads:/downloads
      # - /home/roman/media/arrfam/downloads/completed:/downloads

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Madrid
    volumes:
      - ~/docker/arrfam/.sonarr:/config
      - /home/roman/downloads/tv:/tv
      - /home/roman/downloads:/downloads
      # - /home/roman/media/arrfam/downloads/completed:/downloads

  # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    ports:
      - "9696:9696"
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Madrid
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ~/docker/arrfam/.prowlarr:/config
      - /home/roman/downloads:/downloads
      # - /home/roman/media/arrfam/downloads/watch:/downloads  # transmission watch directory

  samba:
    image: dperson/samba:rpi
    restart: always
    command: '-u "roman;RoMaN" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/roman/media:/media
      - /home/roman/downloads:/downloads

  # https://github.com/dperson/samba
  # samba:
  #   # image: dperson/samba:latest
  #   image: dperson/samba:rpi
  #   restart: always
  #   command: '-u "roman;RoMaN" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no" -s "roman-media;/roman-media;yes;no"'
  #   container_name: samba
  #   # NOTE: see https://github.com/dperson/samba#troubleshooting
  #   ports:
  #     - "139:139"
  #     - "445:445"
  #   environment:
  #     - USERID=1000
  #     - GROUPID=1000
  #     - SHARE=Media;/media
  #     - TZ=Europe/Madrid
  #   volumes:
  #     # - /media:/media
  #     - /etc/localtime:/etc/localtime
  #     - /home/roman/media:/media
  #     # - /home/roman/media:/roman-media
  #     - /home/roman/downloads:/downloads
