version: '3.3'
services:
    docker-controller-bot:
        environment:
            - TELEGRAM_TOKEN=7990304773:AAFvf9WXQoKSfwhW7I6OchQGhgHPpvBz3j8
            - TELEGRAM_ADMIN=188673098
            - CONTAINER_NAME=docker-controller-bot
            - TZ=Europe/Madrid
            #- TELEGRAM_GROUP=
            #- TELEGRAM_THREAD=1
            #- TELEGRAM_NOTIFICATION_CHANNEL=
            - CHECK_UPDATES=1
            - CHECK_UPDATE_EVERY_HOURS=168
            - BUTTON_COLUMNS=3
            #- LANGUAGE=ES
            #- EXTENDED_MESSAGES=0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # NO CAMBIAR
            - ~/docker/controller/.app/schedule:/app/schedule # CAMBIAR LA PARTE IZQUIERDA
        image: dgongut/docker-controller-bot:latest
        container_name: docker-controller-bot
        restart: always
        network_mode: host
        tty: true